spring.application.name=GymTracker
server.port = 8087


#Database config
spring.datasource.url = jdbc:postgresql://localhost:5432/GymTracker
spring.datasource.username = postgres
spring.datasource.password = postgres



springdoc.swagger-ui.tagsSorter=alpha
springdoc.writer-with-order-by-keys=true

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

