spring.application.name=GymTracker
server.port = 8087


#Database config
spring.datasource.url = jdbc:postgresql://localhost:5432/GymTracker
spring.datasource.username = postgres
spring.datasource.password = postgres

spring.jpa.hibernate.ddl-auto = update


