#DB config
spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate

# JWT
jwt.secret=${JWT_SECRET_PROD}

# Logging
logging.level.root=WARN